"""Constants for the Leviton integration."""

from __future__ import annotations

import logging

DOMAIN = "leviton_load_center"
LOGGER = logging.getLogger(__package__)

CONF_TOKEN = "token"
CONF_USER_ID = "user_id"
CONF_VOLTAGE_208 = "voltage_208"
CONF_READ_ONLY = "read_only"
CONF_CALCULATED_CURRENT = "calculated_current"
CONF_HIDE_DUMMY = "hide_dummy"

DEFAULT_VOLTAGE_208 = False
DEFAULT_READ_ONLY = False
DEFAULT_CALCULATED_CURRENT = False
DEFAULT_HIDE_DUMMY = False

VOLTAGE_120 = 120
VOLTAGE_208 = 208
VOLTAGE_240 = 240

# Breaker currentState values from the API
STATE_MANUAL_ON = "ManualON"
STATE_MANUAL_OFF = "ManualOFF"
STATE_COMMUNICATING = "COMMUNICATING"
STATE_NOT_COMMUNICATING = "NotCommunicating"
STATE_COMMUNICATION_FAILURE = "CommunicationFailure"
STATE_UNDEFINED = "UNDEFINED"
STATE_SOFTWARE_TRIP = "SoftwareTrip"
STATE_GFCI_FAULT = "GFCIFault"
STATE_AFCI_MISWIRE = "AFCIMiswire"
STATE_AFCI_PARALLEL_FAULT = "AFCIParallelFault"
STATE_AFCI_SERIAL_ARC_5A = "AFCISerialArc5AFault"
STATE_AFCI_SERIAL_ARC_10A = "AFCISerialArc10AFault"
STATE_AFCI_SERIAL_ARC_15A = "AFCISerialArc15AFault"
STATE_AFCI_SERIAL_ARC_20A = "AFCISerialArc20AFault"
STATE_AFCI_SERIAL_ARC_30A = "AFCISerialArc30AFault"
STATE_OVERCURRENT_TRIP_1 = "OverCurrentTripPhase1"
STATE_OVERCURRENT_TRIP_2 = "OverCurrentTripPhase2"
STATE_OVERLOAD_TRIP = "OverloadTrip"
STATE_SHORT_CIRCUIT_TRIP = "ShortCircuitTrip"
STATE_UPSTREAM_FAULT = "UpstreamFault"

# Breaker remoteState values from the API
STATE_REMOTE_ON = "RemoteON"
STATE_REMOTE_OFF = "RemoteOFF"

# States where the breaker has lost communication
BREAKER_OFFLINE_STATES: frozenset[str] = frozenset({
    STATE_NOT_COMMUNICATING,
    STATE_COMMUNICATION_FAILURE,
    STATE_UNDEFINED,
})

# States where the breaker is physically off or tripped
BREAKER_OFF_STATES: frozenset[str] = frozenset({
    STATE_MANUAL_OFF,
    STATE_SOFTWARE_TRIP,
    STATE_GFCI_FAULT,
    STATE_AFCI_MISWIRE,
    STATE_AFCI_PARALLEL_FAULT,
    STATE_AFCI_SERIAL_ARC_5A,
    STATE_AFCI_SERIAL_ARC_10A,
    STATE_AFCI_SERIAL_ARC_15A,
    STATE_AFCI_SERIAL_ARC_20A,
    STATE_AFCI_SERIAL_ARC_30A,
    STATE_OVERCURRENT_TRIP_1,
    STATE_OVERCURRENT_TRIP_2,
    STATE_OVERLOAD_TRIP,
    STATE_SHORT_CIRCUIT_TRIP,
})
